//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    
    public partial class GetEvaluacion_Result1
    {
        public string cveEvaluacion { get; set; }
        public Nullable<double> Calificacion { get; set; }
        public string cveAplicacion { get; set; }
        public string cveJuez { get; set; }
        public string cveSubcategoria { get; set; }
        public string esFinal { get; set; }
    }
}
