//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiosInstitucionales.Entities.Models
{
    using System;
    
    public partial class GetSubcategorias_Result1
    {
        public string cveSubcategoria { get; set; }
        public string nombre { get; set; }
        public Nullable<int> orden { get; set; }
        public string cveCategoria { get; set; }
    }
}
